In [4]:
import torch
import numpy as np

data = [[1,2],[3,4]]
x_data = torch.tensor(data)

np_array=np.array(data)
x_np = torch.from_numpy(np_array)

print(x_data)
print(x_np)

x_ones = torch.ones_like(x_data)
print(f"Ones Tesnor : \n {x_ones} \n")

x_rand = torch.rand_like(x_data,dtype=torch.float)
print(f'Random Tensor: \n {x_rand} \n')

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])
Ones Tesnor : 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6574, 0.1043],
        [0.1184, 0.8634]]) 



In [5]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f'Random Tensor : \n {rand_tensor}\n')
print(f'Ones Tensor : \n {ones_tensor}\n')
print(f'Zeros Tensor : \n {zeros_tensor}\n')

Random Tensor : 
 tensor([[0.8689, 0.6488, 0.9987],
        [0.1415, 0.4786, 0.9492]])

Ones Tensor : 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor : 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



In [6]:
tensor = torch.rand(3,4)
print(f"shape, datatype, device : {tensor.shape}, {tensor.dtype},{tensor.device}")

shape, datatype, device : torch.Size([3, 4]), torch.float32,cpu


In [7]:
if torch.cuda.is_available():
  tensor=tensor.to('cuda')

In [8]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [11]:
t1 = torch.cat ([tensor,tensor], dim=1)
print (t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1.]])


In [12]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])
